### ISSUE TITLE
Chap 11 not working

### ISSUE THREAD

**Issue by denisM70** [PeterHimschoot/microsoft-blazor-book-3#15]
When will the chapters 11, 12, 13, 15, 17 be available?

**Comment by PeterHimschoot** [comment]
I just updated the packages for ch 11, will do the same for the rest.

**Comment by denisM70** [comment]
Thanks for the quick answer!

**Comment by PeterHimschoot** [comment]
So, everything has been updated to 6.0.13 (latest LTS version)
