### ISSUE TITLE
Ch 4 Component reuse

### ISSUE THREAD

**Issue by ostapsivko** [PeterHimschoot/microsoft-blazor-book-3#9]
Hello Peter!

First of all, thank you for a book. It's a great starting point for me to get to know Blazor and client-side development with C#.

I want to check if I did correct deduction about ch 4, Component reuse. 

Ch04/PizzaPlace/PizzaPlace/Client/Pages/PizzaItem.razor contains code that seems to need to be updated to use ButtonTitle and ButtonClass. Otherwise it overrides any values that are passed in by the ShoppingBasket or PizzaList.

Is this intended to allow reader to deduce what should be adjusted?

**Comment by PeterHimschoot** [comment]
Yes, indeed! Thank you for pointing this out. Looks like I forgot to use the ButtonTitle and ButtonClass properties in the PizzaItem component.
